global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'edge-orion'
    replica: '1'

scrape_configs:
  - job_name: 'trailer-vision-edge'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'edgebox-orion'
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  # - "alerts.yml"

storage:
  tsdb:
    path: /prometheus
    retention.time: 30d

